import type { Workout, Exercise } from './types';

// Curated starter library — 12 high-quality workouts across goals, equipment, durations
// Each is a complete, balanced session that a real person would actually do.

const ex = (
  id: string, name: string, primary: Exercise['primary'],
  equipment: Exercise['equipment'], sets: number, reps: string, rest: number,
  cue?: string, duration_seconds?: number
): Exercise => ({ id, name, primary, equipment, sets, reps, rest_seconds: rest, cue, duration_seconds });

export const SEED_WORKOUTS: Workout[] = [
  // 1 — Push day, dumbbells, intermediate
  {
    id: 'seed-push-db',
    name: 'Push — Dumbbell Power',
    description: 'Classic push split. Hits chest, shoulders, triceps with two compounds and three accessories. Built around dumbbells so it works at home or in the gym.',
    goal: 'hypertrophy',
    difficulty: 'intermediate',
    duration_min: 50,
    primary_muscles: ['chest', 'shoulders', 'triceps'],
    equipment: ['dumbbells', 'bench'],
    source: 'curated',
    tags: ['push', 'upper'],
    created_at: '2026-01-01T00:00:00Z',
    exercises: [
      ex('e1', 'Dumbbell Bench Press', 'chest', ['dumbbells', 'bench'], 4, '8-10', 90, 'Drive elbows under wrists. Squeeze pecs at top.'),
      ex('e2', 'Seated Dumbbell Shoulder Press', 'shoulders', ['dumbbells', 'bench'], 4, '8-10', 90, 'Brace core. Press straight up, no flare.'),
      ex('e3', 'Incline Dumbbell Press', 'chest', ['dumbbells', 'bench'], 3, '10-12', 75, 'Bench at 30°. Slow eccentric.'),
      ex('e4', 'Dumbbell Lateral Raise', 'shoulders', ['dumbbells'], 3, '12-15', 60, 'Lead with elbows. Pause at top.'),
      ex('e5', 'Overhead Dumbbell Triceps Extension', 'triceps', ['dumbbells'], 3, '10-12', 60, 'Elbows tight to head. Stretch the long head.'),
    ],
  },
  // 2 — Pull day, dumbbells + pull-up bar
  {
    id: 'seed-pull-db',
    name: 'Pull — Back & Biceps',
    description: 'Vertical and horizontal pulling for thickness and width. Finish with curls. Add weight to pull-ups when bodyweight gets easy.',
    goal: 'hypertrophy',
    difficulty: 'intermediate',
    duration_min: 50,
    primary_muscles: ['back', 'biceps'],
    equipment: ['dumbbells', 'pullup_bar', 'bench'],
    source: 'curated',
    tags: ['pull', 'upper'],
    created_at: '2026-01-01T00:00:00Z',
    exercises: [
      ex('e1', 'Pull-Up', 'back', ['pullup_bar'], 4, '6-10', 120, 'Squeeze shoulder blades. Full hang.'),
      ex('e2', 'One-Arm Dumbbell Row', 'back', ['dumbbells', 'bench'], 4, '8-10', 90, 'Pull elbow to hip. Don\'t rotate torso.'),
      ex('e3', 'Chest-Supported Row', 'back', ['dumbbells', 'bench'], 3, '10-12', 75, 'Bench at 30°. Squeeze blades together.'),
      ex('e4', 'Dumbbell Hammer Curl', 'biceps', ['dumbbells'], 3, '10-12', 60, 'Neutral grip. Elbow stays pinned.'),
      ex('e5', 'Dumbbell Incline Curl', 'biceps', ['dumbbells', 'bench'], 3, '10-12', 60, 'Lay back, full stretch at bottom.'),
    ],
  },
  // 3 — Leg day
  {
    id: 'seed-legs-1',
    name: 'Legs — Squat Focus',
    description: 'Quad-dominant session built around the back squat. Heavy compound first, then unilateral and accessory work. Walks the line between size and strength.',
    goal: 'hypertrophy',
    difficulty: 'intermediate',
    duration_min: 60,
    primary_muscles: ['quads', 'glutes', 'hamstrings', 'calves'],
    equipment: ['barbell', 'dumbbells', 'bench'],
    source: 'curated',
    tags: ['legs', 'lower'],
    created_at: '2026-01-01T00:00:00Z',
    exercises: [
      ex('e1', 'Barbell Back Squat', 'quads', ['barbell'], 5, '5-8', 150, 'Knees track toes. Brace hard before unrack.'),
      ex('e2', 'Romanian Deadlift', 'hamstrings', ['barbell'], 4, '8-10', 120, 'Push hips back. Bar stays close to legs.'),
      ex('e3', 'Walking Lunge (DB)', 'quads', ['dumbbells'], 3, '10/leg', 90, 'Long step. Knee tracks ankle.'),
      ex('e4', 'Hip Thrust', 'glutes', ['barbell', 'bench'], 3, '10-12', 90, 'Drive through heels. Squeeze glutes at top.'),
      ex('e5', 'Standing Calf Raise', 'calves', ['dumbbells'], 4, '15-20', 60, 'Pause stretch at the bottom.'),
    ],
  },
  // 4 — Full body, bodyweight only, 30min
  {
    id: 'seed-bw-quick',
    name: 'No-Gear 30',
    description: 'Full-body bodyweight circuit. Zero equipment. Done in 30 minutes. Perfect for travel days or a quick morning hit.',
    goal: 'fat_loss',
    difficulty: 'beginner',
    duration_min: 30,
    primary_muscles: ['fullbody'],
    equipment: ['bodyweight'],
    source: 'curated',
    tags: ['quick', 'travel'],
    created_at: '2026-01-01T00:00:00Z',
    exercises: [
      ex('e1', 'Push-Up', 'chest', ['bodyweight'], 4, '12-20', 45, 'Hands under shoulders. Body in a line.'),
      ex('e2', 'Bodyweight Squat', 'quads', ['bodyweight'], 4, '20-25', 45, 'Sit back. Chest up. Full depth.'),
      ex('e3', 'Reverse Lunge', 'glutes', ['bodyweight'], 3, '12/leg', 45, 'Step long. Front knee over ankle.'),
      ex('e4', 'Plank', 'core', ['bodyweight'], 3, 'time', 45, 'Brace abs and glutes hard.', 45),
      ex('e5', 'Mountain Climber', 'cardio', ['bodyweight'], 3, 'time', 30, 'Hips down. Drive knees fast.', 30),
    ],
  },
  // 5 — Strength, barbell, advanced
  {
    id: 'seed-strength-bb',
    name: 'Heavy Day — Big 3',
    description: 'Pure strength session. Squat, bench, deadlift in one. Low reps, long rest. Lift heavy and walk away.',
    goal: 'strength',
    difficulty: 'advanced',
    duration_min: 75,
    primary_muscles: ['quads', 'chest', 'back'],
    equipment: ['barbell', 'bench'],
    source: 'curated',
    tags: ['strength', 'powerlifting'],
    created_at: '2026-01-01T00:00:00Z',
    exercises: [
      ex('e1', 'Back Squat', 'quads', ['barbell'], 5, '3-5', 180, 'Walk it out, brace, descend with control.'),
      ex('e2', 'Bench Press', 'chest', ['barbell', 'bench'], 5, '3-5', 180, 'Tight upper back. Bar to lower chest.'),
      ex('e3', 'Deadlift', 'back', ['barbell'], 4, '3-5', 180, 'Pull the slack out. Push the floor away.'),
      ex('e4', 'Weighted Pull-Up', 'back', ['pullup_bar'], 3, '5-8', 120, 'Add weight. Full ROM.'),
    ],
  },
  // 6 — HIIT cardio
  {
    id: 'seed-hiit-20',
    name: 'HIIT — 20 Minute Burner',
    description: 'Five rounds of work-rest intervals. High-intensity, low-equipment. Builds conditioning and torches calories.',
    goal: 'fat_loss',
    difficulty: 'intermediate',
    duration_min: 20,
    primary_muscles: ['cardio', 'fullbody'],
    equipment: ['bodyweight'],
    source: 'curated',
    tags: ['hiit', 'cardio'],
    created_at: '2026-01-01T00:00:00Z',
    exercises: [
      ex('e1', 'Burpee', 'fullbody', ['bodyweight'], 5, 'time', 20, 'Pace yourself. Full chest to floor.', 40),
      ex('e2', 'Jump Squat', 'quads', ['bodyweight'], 5, 'time', 20, 'Land soft. Explode up.', 40),
      ex('e3', 'Mountain Climber', 'cardio', ['bodyweight'], 5, 'time', 20, 'Fast knees. Hips low.', 40),
      ex('e4', 'High Knees', 'cardio', ['bodyweight'], 5, 'time', 20, 'Knees to waist. Pump arms.', 40),
    ],
  },
  // 7 — Mobility / recovery
  {
    id: 'seed-mob-1',
    name: 'Mobility — Deload Flow',
    description: 'Hip openers, thoracic rotation, hamstring length. Use on rest days or before a heavy session. No equipment.',
    goal: 'mobility',
    difficulty: 'beginner',
    duration_min: 25,
    primary_muscles: ['mobility'],
    equipment: ['bodyweight'],
    source: 'curated',
    tags: ['recovery', 'flexibility'],
    created_at: '2026-01-01T00:00:00Z',
    exercises: [
      ex('e1', 'Cat-Cow', 'mobility', ['bodyweight'], 3, 'time', 15, 'Slow. Move with the breath.', 60),
      ex('e2', 'World\'s Greatest Stretch', 'mobility', ['bodyweight'], 3, '5/side', 30, 'Reach through. Big rotation.'),
      ex('e3', '90/90 Hip Switch', 'mobility', ['bodyweight'], 3, '8/side', 30, 'Push knee down. Hold the stretch.'),
      ex('e4', 'Couch Stretch', 'mobility', ['bodyweight'], 2, 'time', 30, 'Foot up on bench. Squeeze glute.', 60),
      ex('e5', 'Down Dog → Cobra', 'mobility', ['bodyweight'], 3, '8 reps', 30, 'Flow between. Open chest at the top.'),
    ],
  },
  // 8 — Kettlebell session
  {
    id: 'seed-kb-1',
    name: 'Kettlebell Conditioning',
    description: 'Single-bell flow. Builds posterior chain strength and conditioning at the same time. Perfect for a 40-min hit.',
    goal: 'athletic',
    difficulty: 'intermediate',
    duration_min: 40,
    primary_muscles: ['fullbody', 'glutes', 'shoulders'],
    equipment: ['kettlebell'],
    source: 'curated',
    tags: ['kettlebell', 'conditioning'],
    created_at: '2026-01-01T00:00:00Z',
    exercises: [
      ex('e1', 'Kettlebell Swing', 'glutes', ['kettlebell'], 5, '15-20', 60, 'Hinge, not squat. Snap the hips.'),
      ex('e2', 'Goblet Squat', 'quads', ['kettlebell'], 4, '10-12', 60, 'Bell at chest. Sit between heels.'),
      ex('e3', 'Single-Arm KB Press', 'shoulders', ['kettlebell'], 4, '6-8/side', 75, 'Brace hard. Press straight up.'),
      ex('e4', 'KB Clean & Press', 'fullbody', ['kettlebell'], 3, '6/side', 90, 'Smooth clean. Lock out overhead.'),
      ex('e5', 'KB Russian Twist', 'core', ['kettlebell'], 3, '20 total', 45, 'Heels up. Touch bell each side.'),
    ],
  },
  // 9 — Beginner full body, dumbbells
  {
    id: 'seed-beginner-fb',
    name: 'Beginner Full Body',
    description: 'A balanced first workout. Compound movements, moderate reps, gentle progression. Build a base before splitting routines.',
    goal: 'hypertrophy',
    difficulty: 'beginner',
    duration_min: 40,
    primary_muscles: ['fullbody'],
    equipment: ['dumbbells', 'bench'],
    source: 'curated',
    tags: ['beginner', 'fullbody'],
    created_at: '2026-01-01T00:00:00Z',
    exercises: [
      ex('e1', 'Goblet Squat', 'quads', ['dumbbells'], 3, '10-12', 90, 'Hold one bell at chest. Sit between heels.'),
      ex('e2', 'Dumbbell Bench Press', 'chest', ['dumbbells', 'bench'], 3, '10-12', 90, 'Slow lower. Press up under control.'),
      ex('e3', 'One-Arm Dumbbell Row', 'back', ['dumbbells', 'bench'], 3, '10-12/side', 75, 'Pull elbow to hip.'),
      ex('e4', 'Dumbbell Romanian Deadlift', 'hamstrings', ['dumbbells'], 3, '10-12', 75, 'Hinge from hips. Soft knees.'),
      ex('e5', 'Plank', 'core', ['bodyweight'], 3, 'time', 60, 'Body in a line. Brace.', 30),
    ],
  },
  // 10 — Core finisher
  {
    id: 'seed-core-15',
    name: 'Core — 15 Minute Finish',
    description: 'Tack onto the end of any session. Hits all four sides of the trunk. No equipment.',
    goal: 'hypertrophy',
    difficulty: 'beginner',
    duration_min: 15,
    primary_muscles: ['core'],
    equipment: ['bodyweight'],
    source: 'curated',
    tags: ['finisher', 'core'],
    created_at: '2026-01-01T00:00:00Z',
    exercises: [
      ex('e1', 'Hollow Hold', 'core', ['bodyweight'], 3, 'time', 30, 'Lower back glued to floor.', 30),
      ex('e2', 'Side Plank', 'core', ['bodyweight'], 3, 'time/side', 30, 'Stack feet. Drive hips up.', 30),
      ex('e3', 'Dead Bug', 'core', ['bodyweight'], 3, '10/side', 30, 'Press low back into floor.'),
      ex('e4', 'Russian Twist', 'core', ['bodyweight'], 3, '20 total', 30, 'Heels up. Slow rotation.'),
    ],
  },
  // 11 — Upper body bands (travel)
  {
    id: 'seed-bands-upper',
    name: 'Bands — Upper Body Travel',
    description: 'Bands-only upper body. Throw a band in your bag and you\'ve got a full session anywhere. Constant tension, joint-friendly.',
    goal: 'hypertrophy',
    difficulty: 'beginner',
    duration_min: 35,
    primary_muscles: ['chest', 'back', 'shoulders'],
    equipment: ['bands'],
    source: 'curated',
    tags: ['travel', 'bands'],
    created_at: '2026-01-01T00:00:00Z',
    exercises: [
      ex('e1', 'Band Chest Press', 'chest', ['bands'], 4, '12-15', 60, 'Anchor behind. Press out, full extension.'),
      ex('e2', 'Band Row', 'back', ['bands'], 4, '12-15', 60, 'Anchor in front. Squeeze blades.'),
      ex('e3', 'Band Overhead Press', 'shoulders', ['bands'], 3, '10-12', 60, 'Stand on band. Press straight up.'),
      ex('e4', 'Band Pull-Apart', 'back', ['bands'], 3, '15-20', 45, 'Arms straight. Pull band to chest.'),
      ex('e5', 'Band Curl', 'biceps', ['bands'], 3, '12-15', 45, 'Stand on band. Slow eccentric.'),
    ],
  },
  // 12 — 5K running progression
  {
    id: 'seed-run-1',
    name: 'Run — Tempo Intervals',
    description: '4×800m tempo intervals with 90s recovery. Builds aerobic base + lactate tolerance. Use on a track or open road.',
    goal: 'endurance',
    difficulty: 'intermediate',
    duration_min: 35,
    primary_muscles: ['cardio'],
    equipment: ['bodyweight'],
    source: 'curated',
    tags: ['running', 'cardio'],
    created_at: '2026-01-01T00:00:00Z',
    exercises: [
      ex('e1', 'Easy Warm-Up Jog', 'cardio', ['bodyweight'], 1, 'time', 0, 'Conversational pace.', 600),
      ex('e2', 'Tempo 800m', 'cardio', ['bodyweight'], 4, '~3:30', 90, 'Hard but sustainable. ~85% effort.'),
      ex('e3', 'Cool Down Walk', 'cardio', ['bodyweight'], 1, 'time', 0, 'Bring HR back down.', 300),
    ],
  },
];
