-- Persistent storage for images generated by Cerebro's generate_image tool
-- and the Image Lab. Storage blobs live in the `notes` bucket; this table
-- tracks the metadata so they can be browsed after chat is cleared.

CREATE TABLE IF NOT EXISTS public.generated_images (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      TEXT NOT NULL,
  prompt       TEXT NOT NULL,
  storage_path TEXT NOT NULL,
  provider     TEXT,
  source       TEXT NOT NULL CHECK (source IN ('cerebro', 'image_lab')),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_generated_images_user_time
  ON public.generated_images(user_id, created_at DESC);

ALTER TABLE public.generated_images ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users manage their own generated images" ON public.generated_images;
CREATE POLICY "Users manage their own generated images" ON public.generated_images
  FOR ALL USING (auth.jwt() ->> 'sub' = user_id);
